In [1]:
import pickle, os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
resDir = '/egr/research-aidd/menghan1/AnchorDrug/resultBaseLine/'
baselines = [
    # 'pretrainOnly',
    'finetune_all_balancesample.pkl',
    # 'finetune_KMeans',
    # 'finetune_naiveUncertainty1',
    # 'finetune_naiveUncertainty2',
    ]
celllist = ['A549', 'MCF7', 'PC3']
for q in baselines:
    print(q)
    fqlist = [f for f in os.listdir(resDir) if q in f]
    # [print(fqlist[i]) for i in range(len(fqlist))]
    f1_all, precision_all, recall_all = [],[],[]
    for c in celllist:
        fc = [f for f in fqlist if c in f][0]
        print(fc)
        with open(resDir+fc, 'rb') as f:
            data = pickle.load(f)
        print(data[0][2])
        f1_c, precision_c, recall_c = [],[],[]

finetune_all_balancesample.pkl
A549_50_0.001_finetune_all_balancesample.pkl
{0: {'train acc': 0.4993013814193821, 'train f1': 0.5005149099313853, 'train precision label 0': 0.5864311017443165, 'train precision label 1': 0.4109043309999431, 'train precision label 2': 0.5624558927311221, 'train recall label 0': 0.4916911045943304, 'train recall label 1': 0.5710218285352736, 'train recall label 2': 0.43210442905997165, 'test acc': 0.5499688128075404, 'test f1': 0.47680119759304973, 'test precision label 0': 0.31386861313868614, 'test precision label 1': 0.8455385970061637, 'test precision label 2': 0.26054774241302736, 'test recall label 0': 0.5882662457248092, 'test recall label 1': 0.5305981489155961, 'test recall label 2': 0.6323353293413174}, 1: {'train acc': 0.5601866497943688, 'train f1': 0.5621312902873531, 'train precision label 0': 0.6443010022082555, 'train precision label 1': 0.46483379931655794, 'train precision label 2': 0.6142800357746199, 'train recall label 0': 0.570418828

In [3]:
resDir = '/egr/research-aidd/menghan1/AnchorDrug/resultBaseLine/'
baselines = [
    # 'pretrainOnly',
    'finetune_all_balancesample.pkl',
    # 'finetune_KMeans',
    # 'finetune_naiveUncertainty1',
    # 'finetune_naiveUncertainty2',
    ]
celllist = ['A549', 'MCF7', 'PC3']
epoch = 10
for q in baselines:
    print(q)
    fqlist = [f for f in os.listdir(resDir) if q in f]
    # [print(fqlist[i]) for i in range(len(fqlist))]
    f1_all, precision_all, recall_all = [],[],[]
    for c in celllist:
        fc = [f for f in fqlist if c in f][0]
        print(fc)
        with open(resDir+fc, 'rb') as f:
            data = pickle.load(f)
        # [print(i, ':', data[0][2][20][i]) for i in data[0][2][20].keys()]
        f1 = [data[i][2][epoch]['test f1'] for i in range(len(data))]
        # print(f1)
        print(np.mean(f1), np.std(f1))

finetune_all_balancesample.pkl
A549_50_0.001_finetune_all_balancesample.pkl
0.540245545786809 0.009299506298857717
MCF7_50_0.001_finetune_all_balancesample.pkl
0.5550282684215638 0.010814145866954583
PC3_50_0.001_finetune_all_balancesample.pkl
0.548444391319397 0.003133996101028139


In [3]:
for q in baselines:
    print(q)
    fqlist = [f for f in os.listdir(resDir) if q in f]
    f1_all, precision_all, recall_all = [],[],[]
    for c in celllist:
        fc = [f for f in fqlist if c in f][0]
        # print(fc)
        with open(resDir+fc, 'rb') as f:
            data = pickle.load(f)
        f1_c, precision_c, recall_c = [],[],[]
        for g in data[0]:
            # print(g)
            f1_g, precision_g, recall_g = [],[],[]
            for n in range(3):
                acc, f1, precision, recall = data[n][g]
                f1_g.append(f1)
                precision_g.append(precision)
                recall_g.append(recall)
            # print(f1_g)
            # print(precision_g)
            f1_c.append(f1_g)
            precision_c.append(precision_g)
            recall_c.append(recall_g)
        f1_c, precision_c, recall_c = np.array(f1_c), np.array(precision_c), np.array(recall_c)
        # print(f1_c.mean())
        f1_all.append(f1_c)
        precision_all.append(precision_c)
        recall_all.append(recall_c)
    f1_all, precision_all, recall_all = np.array(f1_all), np.array(precision_all), np.array(recall_all)
    # print(f1_all.shape, precision_all.shape, recall_all.shape)
    # ## mean of random
    # print(f1_all.mean(axis=2))
    # print(precision_all.mean(axis=2))
    # ## mean of random and gene
    # print(f1_all.mean(axis=2).mean(axis=1))
    # print(precision_all.mean(axis=2).mean(axis=1))
    ## mean of random and gene and cell
    print(f1_all.mean(axis=2).mean(axis=1).mean(axis=0))
    print(precision_all.mean(axis=2).mean(axis=1).mean(axis=0))
    print(recall_all.mean(axis=2).mean(axis=1).mean(axis=0))

finetune_KMeans
0.3811620347984865
[0.26270031 0.82604469 0.10232356]
[0.32005269 0.73077796 0.15580284]
finetune_naiveUncertainty1
0.38691179167282747
[0.37400843 0.81828258 0.09499705]
[0.20962576 0.83647808 0.11966976]
finetune_naiveUncertainty2
0.3770909997507534
[0.32698699 0.82401937 0.10181969]
[0.24031296 0.80747384 0.12229211]


In [4]:
epoch = ['_10_', '_20_', '_30_', '_40_']

for q in epoch:
    print(q)
    fqlist = [f for f in os.listdir(resDir) if q in f]
    f1_all, precision_all, recall_all = [],[],[]
    for c in celllist:
        fc = [f for f in fqlist if c in f][0]
        # print(fc)
        with open(resDir+fc, 'rb') as f:
            data = pickle.load(f)
        f1_c, precision_c, recall_c = [],[],[]
        for g in data[0]:
            # print(g)
            f1_g, precision_g, recall_g = [],[],[]
            for n in range(3):
                acc, f1, precision, recall = data[n][g]
                f1_g.append(f1)
                precision_g.append(precision)
                recall_g.append(recall)
            # print(f1_g)
            # print(precision_g)
            f1_c.append(f1_g)
            precision_c.append(precision_g)
            recall_c.append(recall_g)
        f1_c, precision_c, recall_c = np.array(f1_c), np.array(precision_c), np.array(recall_c)
        # print(f1_c.mean())
        f1_all.append(f1_c)
        precision_all.append(precision_c)
        recall_all.append(recall_c)
    f1_all, precision_all, recall_all = np.array(f1_all), np.array(precision_all), np.array(recall_all)
    ## mean of random and gene and cell
    print(f1_all.mean(axis=2).mean(axis=1).mean(axis=0))
    print(precision_all.mean(axis=2).mean(axis=1).mean(axis=0))
    print(recall_all.mean(axis=2).mean(axis=1).mean(axis=0))

_10_
0.4204186320812469
[0.48292524 0.82305135 0.24684902]
[0.1998362  0.92003088 0.11337617]
_20_
0.44025893506239494
[0.33653294 0.83165423 0.19598378]
[0.28888569 0.84340084 0.19006334]
_30_
0.4360334131110964
[0.33586376 0.83095622 0.18038512]
[0.28333112 0.84052682 0.18840761]
_40_
0.43932548043566927
[0.32253396 0.83130082 0.19006777]
[0.29616516 0.83331773 0.19782564]
