In [1]:
import pickle, os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
resDir = '/egr/research-aidd/menghan1/AnchorDrug/resultBaseLine/'
baselines = [
    # 'pretrainOnly',
    'finetune_all',
    # 'finetune_KMeans',
    # 'finetune_naiveUncertainty1',
    # 'finetune_naiveUncertainty2',
    ]
# genelist = ['HMGCS1', 'TOP2A', 'DNAJB1', 'PCNA', 'HMOX1']
celllist = ['A549', 'MCF7', 'PC3']

In [3]:
for q in baselines:
    print(q)
    fqlist = [f for f in os.listdir(resDir) if q in f]
    f1_all, precision_all, recall_all = [],[],[]
    for c in celllist:
        fc = [f for f in fqlist if c in f][0]
        print(fc)
        with open(resDir+fc, 'rb') as f:
            data = pickle.load(f)
        print(data)
        f1_c, precision_c, recall_c = [],[],[]

finetune_all
A549_finetune_all_50_0.001.pkl.pkl
[(0.5962644673920576, 0.4957596425755592, array([0.30322233, 0.84538717, 0.29815167]), array([0.5916864 , 0.60929226, 0.51676647]), array([[ 2249,  1215,   337],
       [ 4759, 13232,  3726],
       [  409,  1205,  1726]])), (0.5941853212280823, 0.4961550103493379, array([0.32528107, 0.84766331, 0.27623821]), array([0.56327282, 0.60468757, 0.56107784]), array([[ 2141,  1240,   420],
       [ 4095, 13132,  4490],
       [  346,  1120,  1874]])), (0.5960219003395939, 0.4967128262185298, array([0.31500808, 0.84731404, 0.28653074]), array([0.563799  , 0.60791085, 0.55538922]), array([[ 2143,  1247,   411],
       [ 4307, 13202,  4208],
       [  353,  1132,  1855]]))]
MCF7_finetune_all_50_0.001.pkl.pkl
[(0.5983761971899461, 0.5067098780826761, array([0.36584194, 0.81406243, 0.29846555]), array([0.51219102, 0.6250084 , 0.54695828]), array([[ 3046,  2264,   637],
       [ 4798, 18594,  6358],
       [  482,  1983,  2976]])), (0.6261121104574846

In [3]:
for q in baselines:
    print(q)
    fqlist = [f for f in os.listdir(resDir) if q in f]
    f1_all, precision_all, recall_all = [],[],[]
    for c in celllist:
        fc = [f for f in fqlist if c in f][0]
        # print(fc)
        with open(resDir+fc, 'rb') as f:
            data = pickle.load(f)
        f1_c, precision_c, recall_c = [],[],[]
        for g in data[0]:
            # print(g)
            f1_g, precision_g, recall_g = [],[],[]
            for n in range(3):
                acc, f1, precision, recall = data[n][g]
                f1_g.append(f1)
                precision_g.append(precision)
                recall_g.append(recall)
            # print(f1_g)
            # print(precision_g)
            f1_c.append(f1_g)
            precision_c.append(precision_g)
            recall_c.append(recall_g)
        f1_c, precision_c, recall_c = np.array(f1_c), np.array(precision_c), np.array(recall_c)
        # print(f1_c.mean())
        f1_all.append(f1_c)
        precision_all.append(precision_c)
        recall_all.append(recall_c)
    f1_all, precision_all, recall_all = np.array(f1_all), np.array(precision_all), np.array(recall_all)
    # print(f1_all.shape, precision_all.shape, recall_all.shape)
    # ## mean of random
    # print(f1_all.mean(axis=2))
    # print(precision_all.mean(axis=2))
    # ## mean of random and gene
    # print(f1_all.mean(axis=2).mean(axis=1))
    # print(precision_all.mean(axis=2).mean(axis=1))
    ## mean of random and gene and cell
    print(f1_all.mean(axis=2).mean(axis=1).mean(axis=0))
    print(precision_all.mean(axis=2).mean(axis=1).mean(axis=0))
    print(recall_all.mean(axis=2).mean(axis=1).mean(axis=0))

finetune_KMeans
0.3811620347984865
[0.26270031 0.82604469 0.10232356]
[0.32005269 0.73077796 0.15580284]
finetune_naiveUncertainty1
0.38691179167282747
[0.37400843 0.81828258 0.09499705]
[0.20962576 0.83647808 0.11966976]
finetune_naiveUncertainty2
0.3770909997507534
[0.32698699 0.82401937 0.10181969]
[0.24031296 0.80747384 0.12229211]


In [4]:
epoch = ['_10_', '_20_', '_30_', '_40_']

for q in epoch:
    print(q)
    fqlist = [f for f in os.listdir(resDir) if q in f]
    f1_all, precision_all, recall_all = [],[],[]
    for c in celllist:
        fc = [f for f in fqlist if c in f][0]
        # print(fc)
        with open(resDir+fc, 'rb') as f:
            data = pickle.load(f)
        f1_c, precision_c, recall_c = [],[],[]
        for g in data[0]:
            # print(g)
            f1_g, precision_g, recall_g = [],[],[]
            for n in range(3):
                acc, f1, precision, recall = data[n][g]
                f1_g.append(f1)
                precision_g.append(precision)
                recall_g.append(recall)
            # print(f1_g)
            # print(precision_g)
            f1_c.append(f1_g)
            precision_c.append(precision_g)
            recall_c.append(recall_g)
        f1_c, precision_c, recall_c = np.array(f1_c), np.array(precision_c), np.array(recall_c)
        # print(f1_c.mean())
        f1_all.append(f1_c)
        precision_all.append(precision_c)
        recall_all.append(recall_c)
    f1_all, precision_all, recall_all = np.array(f1_all), np.array(precision_all), np.array(recall_all)
    ## mean of random and gene and cell
    print(f1_all.mean(axis=2).mean(axis=1).mean(axis=0))
    print(precision_all.mean(axis=2).mean(axis=1).mean(axis=0))
    print(recall_all.mean(axis=2).mean(axis=1).mean(axis=0))

_10_
0.4204186320812469
[0.48292524 0.82305135 0.24684902]
[0.1998362  0.92003088 0.11337617]
_20_
0.44025893506239494
[0.33653294 0.83165423 0.19598378]
[0.28888569 0.84340084 0.19006334]
_30_
0.4360334131110964
[0.33586376 0.83095622 0.18038512]
[0.28333112 0.84052682 0.18840761]
_40_
0.43932548043566927
[0.32253396 0.83130082 0.19006777]
[0.29616516 0.83331773 0.19782564]
