In [1]:
import pickle, os
import numpy as np
import pandas as pd

In [2]:
resDir = '/egr/research-aidd/menghan1/AnchorDrug/ActiveLearning/results'
ctgr = os.listdir(resDir)
genelist = ['HMGCS1', 'TOP2A', 'DNAJB1', 'PCNA', 'HMOX1']

In [ ]:
def calMeanStd(f):
    

In [3]:
dictData = {key:{} for key in ctgr}
for c in ctgr:
    print(c)
    dictTmp = dictData[c]
    for cell in ['A549', 'MCF7', 'PC3']:
        mtcPath = f'/egr/research-aidd/menghan1/AnchorDrug/ActiveLearning/results/{c}/LINCS_{cell}_LeastConfidence_10_0_30.pkl'
        with open(mtcPath, 'rb') as f:
            all_acc,all_f1 = pickle.load(f)
        all_acc, all_f1 = np.array(all_acc), np.array(all_f1)
        acc = np.mean(all_acc, axis=0)[-1]
        f1 = np.mean(all_f1, axis=0)[-1]
        print(f1)
        dictTmp[cell] = {key:value for key, value in zip(genelist, f1)}
        # print(np.mean(all_acc, axis=0)[-1].shape, np.mean(all_f1, axis=0)[-1].shape)

naiveUncertainty1
[0.36989043 0.41614957 0.34388278 0.37021526 0.40740987]
[0.33824712 0.36313754 0.40452591 0.38648133 0.32071644]
[0.34265422 0.4716433  0.42114562 0.37190128 0.44451495]
naiveUncertainty2
[0.39584178 0.42031171 0.32116711 0.36253325 0.42037577]
[0.39920689 0.36968959 0.35223201 0.3911798  0.34558404]
[0.35156536 0.38668401 0.37342507 0.37638575 0.43639968]


In [7]:
for c in ctgr:
    df = pd.DataFrame.from_dict(dictData[c])
    print(df)
    arr = df.to_numpy()
    print(arr.mean(), arr.std())

            A549      MCF7       PC3
HMGCS1  0.369890  0.338247  0.342654
TOP2A   0.416150  0.363138  0.471643
DNAJB1  0.343883  0.404526  0.421146
PCNA    0.370215  0.386481  0.371901
HMOX1   0.407410  0.320716  0.444515
0.3848343755647571 0.040914194058291845
            A549      MCF7       PC3
HMGCS1  0.395842  0.399207  0.351565
TOP2A   0.420312  0.369690  0.386684
DNAJB1  0.321167  0.352232  0.373425
PCNA    0.362533  0.391180  0.376386
HMOX1   0.420376  0.345584  0.436400
0.3801721214574353 0.030461220760161854
